version: '3.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api-platform
      POSTGRES_PASSWORD: !ChangeMe!
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data