version: '3.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set or empty}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set or empty}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set or empty}
    volumes:
      - ./home/Users/mena0018/production/docker/db/data:/var/lib/postgresql/data

  php:
    image: ${PHP_IMAGE:?PHP_IMAGE is not set or empty}:${APP_VERSION:?APP_VERSION is not set or empty}
    restart: always
    depends_on:
      - db
    environment:
      APP_DEBUG : ${APP_DEBUG}
  api:
    build:
      context: .
      target: api_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro   # :ro => short syntaxe for Read Only
    ports:
      - "8082:80"
