version: '3.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set or empty}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set or empty}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set or empty}
    volumes:
      - ./home/Users/mena0018/production/docker/db/data:/var/lib/postgresql/data
